### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by DamRCorba** [Agustorreblanca/Maquina-Estado#1]
Hola Agustin, Esta bastante bien soolo hay un par de correcciones a realizar.

La primera es administrativa, el readme.md deberia estar en este repositorio en el cual puedo escribirte los issue para correccion. 

Con respecto al diagrama. El estado de alarma deberia ser uno solo, y este deberia elegir que mensaje accionar.

Saludos

**Comment by Agustorreblanca** [comment]
Hola profe, como corrijo la parte administrativa?

**Comment by DamRCorba** [comment]
@Agustorreblanca, como estas? veo que no tenes avances sobre el tp. Hice una clase exclusiva de este tema, la viste?

te dejo el link https://youtu.be/C5bXlORIaGo

cualquier cosa avisa.

**Comment by Agustorreblanca** [comment]
Hola profe, justo estaba pensando en el tp. Actualmente estoy preparando
otros exámenes y por eso no envié de nuevo el tp. En caso de que vuelva a
tener errores en la próxima entrega se considerará desaprobado?

**Comment by DamRCorba** [comment]
No, pero para la promocion tiene que estar aprobado sin observaciones antes del 3/12. Si lo aprobas despues de esa fecha, no podes promocionar, pero si podes aprobar la materia e ir a final. 

Podes pedir correcciones tantas veces como quieras, no influye en la nota.

**Comment by Agustorreblanca** [comment]
Hola profe estoy haciendo el tp y cuando quiero subir la foto de mi
diagrama de estados, al abrir el link de la imagen, se ve muy chica y no se
entiende el dibujo. Cómo hago para aumentarle el tamaño a la imagen??

**Comment by DamRCorba** [comment]
Con un editor de imagenes. La unica forma de agrandarlo es mejorando la resolucion.

**Comment by Agustorreblanca** [comment]
Yo lo que estoy haciendo es subir la imagen a internet y copiar en el
código el link, como hizo usted. Pero la foto queda muy chica

**Comment by DamRCorba** [comment]
Por favor sigamos en el otro repo. lo unico que esta mal en el readme es sintaxis que pusiste imagine cuando es image
